### ISSUE TITLE
Invalid path alias: @frontend/views/private/rs-plugin

### ISSUE THREAD

**Issue by hdushku** [WadeShuler/yii2-sliderrevolution#1]
I am trying it on a basic app
Invalid path alias: @frontend/views/private/rs-plugin
Good extension

**Comment by WadeShuler** [comment]
You get that error because your supposed to edit that path to your copy of Slider Revolution!

As the comment next to that line indicates, it is the path to your Slider Revolution directory. Slider Revolution **is not** included. You either A) Need to already own it, or B) go buy it.

Once you have Slider Revolution, copy the whole "rs-plugin" directory and place it somewhere/anywhere in your app. Then point to it in the `pluginLocation` parameter.

**Comment by hdushku** [comment]
Ok
Thanks
